#
# Makefile for Provenance LSM
#
obj-$(CONFIG_SECURITY_PROVENANCE) := query.o

query-y := register.o

ccflags-y := -I$(srctree)/security/provenance/include -I$(srctree)/security/provenance/query/include
